_commit: 48dbc8c
_src_path: git@github.com:mizucopo/repo-template.git
author_name: みず
chrome_extension_description: 音声認識でYouTube Liveにコメント投稿
chrome_extension_name: Voice Live Comment
chrome_extension_release_notes: Chrome Extension distribution package for {version}.
chrome_extension_release_package_root_directory: .
chrome_extension_release_title: Chrome Extension {version}
chrome_extension_release_zip_name: chrome-extension-{version}.zip
chrome_extension_version: 1.5.0
node_version: '24'
use_chrome_extension: true
use_docker: false
use_gh_actions_chrome_extension_release: true
use_gh_actions_pr_tag_check: true
use_gh_actions_release: false
use_mit_license: true
use_python: false
use_rust: false
use_tauri: false
