_commit: d1bd4f8
_src_path: git@github.com:mizucopo/repo-template.git
author_name: みず
chrome_extension_description: 音声認識でYouTube Liveにコメント投稿
chrome_extension_name: Voice Live Comment
chrome_extension_version: 1.4.1
node_version: '22'
use_chrome_extension: true
use_docker: false
use_gh_actions_chrome_extension_release: false
use_gh_actions_pr_tag_check: false
use_gh_actions_release: false
use_mit_license: true
use_python: false
use_rust: false
use_tauri: false
